## 1. Write a Python Program to Add Two Matrices?

In [3]:
# Solution-1
m1 = [[7,9,1],
    [0 ,4,3],
    [8 ,3,6]]
 
m2 = [[9,7,1],
    [8,7,3],
    [4,1,5]]

results = [
    [0,0,0],
    [0,0,0],
    [0,0,0]]

## iterate and add matrix
for i in range(len(m1)): 
    for j in range(len(m1[0])):
        results[i][j] = m1[i][j] + m2[i][j]

# show result
for result in results:
    print(result)

[16, 16, 2]
[8, 11, 6]
[12, 4, 11]


In [6]:
# Solution-2
import numpy as np

m1 = np.array([[7,9,1],
    [0 ,4,3],
    [8 ,3,6]])
m2 = np.array([[9,7,1],
    [8,7,3],
    [4,1,5]])

results = np.add(m1, m2)
print(results)

[[16 16  2]
 [ 8 11  6]
 [12  4 11]]


## 2. Write a Python Program to Multiply Two Matrices?

In [8]:
# Solution-1
m1 = [[7,9,1],
    [0 ,4,3],
    [8 ,3,6]]
 
m2 = [[9,7,1],
    [8,7,3],
    [4,1,5]]
results = [
    [1,1,1],
    [1,1,1],
    [1,1,1]]

for i in range(len(m1)): 
    for j in range(len(m1[0])):
        results[i][j] = m1[i][j] * m2[i][j]

for result in results:
    print(result)

[63, 63, 1]
[0, 28, 9]
[32, 3, 30]


In [10]:
# Solution-2
import numpy as np

m1 = np.array([[7,9,1],
    [0 ,4,3],
    [8 ,3,6]])
m2 = np.array([[9,7,1],
    [8,7,3],
    [4,1,5]])

results = np.multiply(m1, m2)
print(results)

[[63 63  1]
 [ 0 28  9]
 [32  3 30]]


## 3. Write a Python Program to Transpose a Matrix?

In [12]:
# Solution-1
matrix = [[7,9,1],
    [0 ,4,3],
    [8 ,3,6]]

results = [
    [0,0,0],
    [0,0,0],
    [0,0,0]]

for i in range(len(matrix)): 
    for j in range(len(matrix[0])):
        results[j][i] = matrix[i][j]

# show result
for result in results:
    print(result)

[7, 0, 8]
[9, 4, 3]
[1, 3, 6]


In [15]:
# Solution-2
import numpy as np

matrix = np.array([[7,9,1],
    [0 ,4,3],
    [8 ,3,6]])

results = matrix.transpose()
print(results)

[[7 0 8]
 [9 4 3]
 [1 3 6]]


## 4. Write a Python Program to Sort Words in Alphabetic Order?

In [19]:
# take input
sentence = input('Enter a sentence: ')

# split sentance
words = sentence.split()

# sort words
sorted_words = sorted(words, key=lambda s: s.lower())
print('Sorted Word: ')
for word in sorted_words:
    print(word)

Enter a sentence: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text
Sorted Word: 
and
been
dummy
dummy
has
industry's
industry.
Ipsum
Ipsum
is
Lorem
Lorem
of
printing
simply
standard
text
text
the
the
typesetting


## 5. Write a Python Program to Remove Punctuation From a String?

In [21]:
# punctuation
punctuations = '''!()-[]{};:='"\,<>./?@#$%^&*_~'''

# take input
sentence = input("Enter a string: ")

# remove punctuation
results = ""
for char in sentence:
    if char not in punctuations:
        results = results + char

print(results)

Enter a string: Lorem ##Ipsum ====is simply dummy ---text of the printing and @typesetting industry. @--Lorem Ipsum has been^^^ the industry's standard dummy text.
Lorem Ipsum is simply dummy text of the printing and typesetting industry Lorem Ipsum has been the industrys standard dummy text
